---

- name: create user group
  user:
    name: "{{ sickrage_user }}"
    system: true
    state: present

- name: create user
  user:
    name: "{{ sickrage_user }}"
    group: "{{ sickrage_user }}"
    system: true
    state: present

- name: ensure dependencies are installed for Debian systems
  apt:
    pkg: "{{item}}"
    state: "present"
  when: ansible_os_family == 'Debian'
  with_items:
    - python-cheetah
    - python-pip
  tags: sickrage

- name: ensure dependencies are installed for RedHat systems
  yum:
    pkg: "{{item}}"
    state: "present"
  when: ansible_os_family == 'RedHat'
  with_items:
    - python-cheetah
    - python-pip
  tags: sickrage

- name: ensure the install dir is available
  file: path={{ sickrage_install_dir }}
        state=directory
        owner={{ sickrage_user }} group={{ sickrage_user }} mode=755
  become: yes
  tags: sickrage

- name: ensure the git repository is checked-out
  git: repo={{ sickrage_github_repo }}
       dest={{ sickrage_install_dir }}
       accept_hostkey=yes
  tags: sickrage

- name: install requirements
  pip:
    requirements: "{{ sickrage_install_dir }}/requirements.txt"

- name: ensure start-up config file is present
  template: src=sickrage.j2
            dest=/etc/default/sickrage
            owner={{ sickrage_user }} mode=755
  become: yes
  tags: sickrage

- name: ensure start-up script is configured for Debian systems
  file: src='{{ sickrage_install_dir }}/runscripts/init.ubuntu'
        dest=/etc/init.d/sickrage
        state=link
  become: yes
  when: ansible_os_family == 'Debian'
  tags: sickrage

- name: ensure start-up script is configured for RedHat systems
  file: src='{{ sickrage_install_dir }}/init.fedora'
        dest=/etc/init.d/sickrage
        state=link
  become: yes
  when: ansible_os_family == 'RedHat'
  tags: sickrage

- name: ensure the sickrage service is enabled at boot
  service: name=sickrage enabled=true state=started
  become: yes
  tags: sickrage
